"use client"
// import type { Metadata } from 'next'
import { useEffect, useState } from 'react';
import { Inter } from 'next/font/google'
// import { headers } from 'next/headers'
import type { ReactNode } from 'react'
import { cookieToInitialState, State } from 'wagmi'
import './globals.css'

import { getConfig } from '../wagmi'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Wagmi',
//   description: 'Generated by create-wagmi',
// }

export default function RootLayout(props: { children: ReactNode }) {
  const [initialState, setInitialState] = useState<State>();

  useEffect(() => {
    const initialState = cookieToInitialState(
      getConfig(),
      // headers().get('cookie'),
      document.cookie
    )
    setInitialState(initialState)
}, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers 
        initialState={initialState}
        >{props.children}</Providers>
      </body>
    </html>
  )
}
